from __future__ import annotations

import streamlit as st

from tournament_tracker.branding import render_bottom_decoration, render_page_intro
from tournament_tracker.bootstrap import get_runtime_services
from tournament_tracker.services.errors import ValidationError
from tournament_tracker.session import logout_user, render_sidebar, require_admin

st.set_page_config(page_title="Admin Backup and Restore", page_icon="💾", layout="wide")

services = get_runtime_services()
admin_user = require_admin(services, current_page="pages/11_Admin_Backup_Restore.py")
render_sidebar(admin_user)

render_page_intro("Backup and Restore", "Export the full tournament state or replace it from a trusted backup.", eyebrow="Admin")
st.warning(
    "Backups contain sensitive data, including password hashes, profile photos, and full tournament history. "
    "Handle backup files securely."
)

offsite_status = services.backup_service.get_offsite_backup_status()

st.subheader("Automatic Off-Site Backup")
with st.container(border=True):
    st.markdown(f"**Status:** {offsite_status.status_label}")
    st.caption(offsite_status.detail_message)
    st.write(f"Provider: {offsite_status.provider_label}")
    st.write(f"Bucket: {offsite_status.bucket or 'Not configured'}")
    st.write(f"Endpoint: {offsite_status.endpoint or 'Not configured'}")
    st.write(f"Region: {offsite_status.region or 'Not configured'}")
    st.write(f"Prefix: {offsite_status.prefix or '-'}")
    st.write(f"Last successful backup: {offsite_status.last_success_at or 'Never'}")
    if offsite_status.last_object_key:
        st.caption(f"Latest object key: `{offsite_status.last_object_key}`")
    if offsite_status.last_error_message:
        st.error(
            "Latest backup error"
            + (f" ({offsite_status.last_error_at})" if offsite_status.last_error_at else "")
            + f": {offsite_status.last_error_message}"
        )
    if st.button("Run off-site backup now", width="stretch", key="run_offsite_backup_now"):
        result = services.backup_service.run_offsite_backup_now()
        if result.success:
            st.success(result.message)
            st.rerun()
        elif result.attempted:
            st.error(result.message)
        else:
            st.info(result.message)

with st.expander("Streamlit Cloud secrets template", expanded=not offsite_status.configured):
    st.caption(
        "Paste this into your app's Secrets in Streamlit Community Cloud, then save and reboot the app."
    )
    st.code(services.backup_service.get_streamlit_secrets_template(), language="toml")
    st.markdown(
        "Backblaze setup checklist:\n"
        "1. Create a **private** bucket in B2 Cloud Storage.\n"
        "2. Open **Application Keys** and create a new key for that bucket.\n"
        "3. Use a key with upload permission for that bucket. If Backblaze shows simple presets, `Read and Write` is the safest choice.\n"
        "4. Copy the **S3 Endpoint**, **keyID**, and **applicationKey** from Backblaze.\n"
        "5. Paste them into Streamlit Cloud secrets using the template above."
    )

st.divider()
st.subheader("Export full state")
st.caption(
    "This exports the entire current database state (users, credentials hashes, invitations, profiles, matches, results, and doubler data)."
)

export_filename, export_bytes = services.backup_service.export_snapshot()
st.download_button(
    label="Download full backup",
    data=export_bytes,
    file_name=export_filename,
    mime="application/octet-stream",
    width="stretch",
)

st.divider()
st.subheader("Import full state")
st.caption(
    "Importing will replace the current database completely. Use only backups generated by this app."
)

uploaded_backup = st.file_uploader(
    "Upload backup file",
    type=["sqlite3", "db", "sqlite", "bak"],
    accept_multiple_files=False,
)
confirm_import = st.checkbox(
    "I understand this will overwrite the current app state.",
    value=False,
)

if st.button("Import backup and replace current state", type="primary", width="stretch"):
    if uploaded_backup is None:
        st.error("Please upload a backup file first.")
    elif not confirm_import:
        st.error("Please confirm overwrite before importing.")
    else:
        try:
            services.backup_service.import_snapshot(uploaded_backup.getvalue())

            logout_user(services)
            st.cache_data.clear()
            st.cache_resource.clear()

            st.success("Backup imported successfully. Please log in again.")
            st.rerun()
        except ValidationError as exc:
            st.error(str(exc))
        except Exception:
            st.error("Import failed. The uploaded file may be invalid or incompatible.")

st.divider()
st.subheader("Debug State Tools")
st.caption(
    "These tools are meant for fast testing. They replace the current database, log you out, and force the app to reload state."
)

demo_snapshot_path = services.backup_service.get_demo_halfway_snapshot_path()
with st.container(border=True):
    st.markdown("**Load fake half-way demo state**")
    st.caption(
        "Replaces the current database with the bundled half-way snapshot from "
        f"`{demo_snapshot_path.as_posix()}`. "
        "After loading, log in with the demo admin credentials `admin / 1234`."
    )
    confirm_demo_load = st.checkbox(
        "I understand this will replace the current state with the fake half-way data.",
        key="confirm_demo_load",
        value=False,
    )
    if st.button("Load fake half-way data", width="stretch", key="load_demo_halfway_btn"):
        if not confirm_demo_load:
            st.error("Please confirm replacement before loading the fake half-way data.")
        else:
            try:
                services.backup_service.load_demo_halfway_state()
                logout_user(services)
                st.cache_data.clear()
                st.cache_resource.clear()
                st.success("The fake half-way state has been loaded. Please log in again.")
                st.rerun()
            except ValidationError as exc:
                st.error(str(exc))
            except Exception:
                st.error("Loading the fake half-way state failed.")

with st.container(border=True):
    st.markdown("**Nuclear reset to fresh state**")
    st.caption(
        "Deletes all participant usage data, match history, invites, and participant accounts, then recreates a clean database. "
        "The current admin account is preserved so you can log back in immediately after the reset."
    )
    confirm_fresh_reset = st.checkbox(
        "I understand this will wipe all participant data and accounts from the live database.",
        key="confirm_fresh_reset",
        value=False,
    )
    if st.button("Reset to fresh state", width="stretch", type="secondary", key="fresh_reset_btn"):
        if not confirm_fresh_reset:
            st.error("Please confirm the full wipe before resetting to a fresh state.")
        else:
            try:
                services.backup_service.reset_to_fresh_state(preserve_admin_user_id=admin_user.id)
                logout_user(services)
                st.cache_data.clear()
                st.cache_resource.clear()
                st.success("Fresh state created. Log in again with your current admin credentials.")
                st.rerun()
            except ValidationError as exc:
                st.error(str(exc))
            except Exception:
                st.error("Fresh reset failed.")

render_bottom_decoration()
