from __future__ import annotations

import streamlit as st

from tournament_tracker.branding import render_bottom_decoration, render_page_intro
from tournament_tracker.bootstrap import get_services
from tournament_tracker.services.errors import ValidationError
from tournament_tracker.session import logout_user, render_sidebar, require_admin

st.set_page_config(page_title="Admin Backup and Restore", page_icon="💾", layout="wide")

services = get_services()
admin_user = require_admin(services)
render_sidebar(admin_user)

render_page_intro("Backup and Restore", "Export the full tournament state or replace it from a trusted backup.", eyebrow="Admin")
st.warning(
    "Backups contain sensitive data, including password hashes, profile photos, and full tournament history. "
    "Handle backup files securely."
)

st.subheader("Export full state")
st.caption(
    "This exports the entire current database state (users, credentials hashes, invitations, profiles, matches, results, and doubler data)."
)

export_filename, export_bytes = services.backup_service.export_snapshot()
st.download_button(
    label="Download full backup",
    data=export_bytes,
    file_name=export_filename,
    mime="application/octet-stream",
    width="stretch",
)

st.divider()
st.subheader("Import full state")
st.caption(
    "Importing will replace the current database completely. Use only backups generated by this app."
)

uploaded_backup = st.file_uploader(
    "Upload backup file",
    type=["sqlite3", "db", "sqlite", "bak"],
    accept_multiple_files=False,
)
confirm_import = st.checkbox(
    "I understand this will overwrite the current app state.",
    value=False,
)

if st.button("Import backup and replace current state", type="primary", width="stretch"):
    if uploaded_backup is None:
        st.error("Please upload a backup file first.")
    elif not confirm_import:
        st.error("Please confirm overwrite before importing.")
    else:
        try:
            services.backup_service.import_snapshot(uploaded_backup.getvalue())

            logout_user()
            st.cache_data.clear()
            st.cache_resource.clear()

            st.success("Backup imported successfully. Please log in again.")
            st.rerun()
        except ValidationError as exc:
            st.error(str(exc))
        except Exception:
            st.error("Import failed. The uploaded file may be invalid or incompatible.")

render_bottom_decoration()
